
# Key debouncing settings (in milliseconds)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# PMW3610 optical sensor settings
CONFIG_SPI=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=14
CONFIG_ZMK_POINTING=y
